[build]
  publish = "build"
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

